eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

frontend:
  url: http://localhost:4200

spring:
  jpa:
    generate-ddl: true
    hibernate:
        ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/production_queue
    username: root
    password: haifa3012
    driver-class-name: com.mysql.cj.jdbc.Driver