apiVersion : apps/v1
kind: Deployment
metadata:
  name: orderproduction 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderproduction
  template:
    metadata:
      labels:
        app: orderproduction 
    spec:
      containers:
        - name: orderproduction 
          image: pizzastorm.azurecr.io/orderproduction
          resources:
            limits:
              memory: "1G"
              cpu: "500m"
          ports:
            - containerPort: 9003
          imagePullPolicy: Always
